### ISSUE TITLE
Script crashes because it tries to (yaml) map values in my DAG because of colons in the .py

### ISSUE THREAD

**Issue by thomasglaser** [feluelle/airflow-diagrams#78]
I get an ScannerError saying `ScannerError: mapping values are not allowed here in "file.py", line 18, column 12` when i try to `airflow-diagrams generate --from-file file.py'. I wonder why this happends, because every DAG file has at least `default_args = {
    "owner": "myself",
    "depends_on_past": False, ...` in it, which looks like the source of the problem to me. Every if statement in the DAG file throws an error, because it uses a colon. Is this also a problem by not using --from-file ?

**Comment by feluelle** [comment]
Closing as it is a duplicate to #77.
