### ISSUE TITLE
TaskIds that contain numbers or dashes are not supported

### ISSUE THREAD

**Issue by nathadfield** [feluelle/airflow-diagrams#8]
If you have a DAG which contains tasks where the id contains either numbers or dashes then, although the diagram Python file is created, it cannot be run to generate the diagram image.

e.g.

```
from diagrams import Diagram
from diagrams.generic.blank import Blank

with Diagram("airbyte", show=False):
    airbyte-job_sensor = Blank("airbyte_job_sensor")
    airbyte_trigger_async = Blank("airbyte_trigger_async")
    
    airbyte_trigger_async >> [airbyte_job_sensor]
```

```
➜  airflow-diagrams git:(master) ✗ python3 examples/airbyte_diagrams.py
  File "/Users/nathan/Projects/airflow-diagrams/examples/airbyte_diagrams.py", line 5
    airbyte-job_sensor = Blank("airbyte_job_sensor")
    ^
SyntaxError: cannot assign to operator
```

**Comment by feluelle** [comment]
Thank you @nathadfield for reporting this.

This is indeed an issue. I will try to fix it in the next patch. Or if you want feel free to open a PR :)

**Comment by feluelle** [comment]
You can see [here](https://github.com/feluelle/airflow-diagrams/blob/master/airflow_diagrams/diagram.jinja2#L6-L11) how the variables will be generated. We could simply do a `node["task_id"]|replace("-", "_")` and `edge["task_id"]|replace("-", "_")`

**Comment by feluelle** [comment]
Yes we can remove/replace them with a regex expression easily as well.

**Comment by nathadfield** [comment]
FYI - I also noticed that DAGs which use TaskGroups also generate invalid diagram variables.

**Comment by feluelle** [comment]
Because of the `.`?

**Comment by feluelle** [comment]
If that's the case, the Pr should also fix this as it is hashing it and every hash prefixed with an underscore should be a valid python variable.

**Comment by feluelle** [comment]
@nathadfield could you please test if this is working now. You can install the latest release (candidate) by running `pip install --pre airflow-diagrams`. It should install `1.0.1rc1`.

**Comment by nathadfield** [comment]
> Because of the `.`?

Yep! I'll certainly take a look at the RC tomorrow.

**Comment by nathadfield** [comment]
@feluelle So, your changes do look like they fie the issues with task_ids although the node labelling is a bit of a mess.

<img width="459" alt="Screenshot 2022-01-21 at 09 02 41" src="https://user-images.githubusercontent.com/967119/150498317-92ac59f8-cedc-4aed-a6b3-704767f0748c.png">

This is perhaps for another version but might it be a good idea to put task groups into clusters?

**Comment by feluelle** [comment]
Great idea. Let's move this to a different issue, please. And I would also add that to a minor release instead of a patch release. So will continue today with releasing `1.0.1`.
