### ISSUE TITLE
Diagram images don't seem to be generated correctly

### ISSUE THREAD

**Issue by nathadfield** [feluelle/airflow-diagrams#9]
I installed airflow-diagrams as per the instructions (FYI - I also had to install Graphviz, currently running 2.50.0) but just trying to run the example diagrams the returned image seemed to be lacking in detail.

![airbyte](https://user-images.githubusercontent.com/967119/150121066-cf4c0280-4a15-4c0f-860c-04b664271cdc.png)

**Comment by feluelle** [comment]
This is because it cannot find diagram nodes for Airbyte and therefore falls back to [blank](https://diagrams.mingrammer.com/docs/nodes/generic#genericblank) node. You can set in a mapping file a mapping for Airbyte to sth. else. :)

**Comment by nathadfield** [comment]
Would be better if the blank node was at least just an empty box rather than nothing though.

**Comment by feluelle** [comment]
Do you have a node in mind we can use as default? I am up for anything generic that looks better than this :)

**Comment by nathadfield** [comment]
Not sure.  Maybe a custom image?

https://diagrams.mingrammer.com/docs/nodes/custom

**Comment by feluelle** [comment]
Yes, sounds good 👍
